translations = {
    'Spanish': {
        'Hello': 'Hola',
        'Goodbye': 'Adiós',
        'Thank you': 'Gracias',
        'Please': 'Por favor',
        'Sorry': 'Lo siento',
        'Yes': 'Sí',
        'No': 'No',
        'Excuse me': 'Perdón',
        'Good morning': 'Buenos días',
        'Good night': 'Buenas noches',
        'How are you?': '¿Cómo estás?',
        'I love you': 'Te quiero',
        'What is your name?': '¿Cuál es tu nombre?',
        'My name is...': 'Mi nombre es...',
        'Where are you from?': '¿De dónde eres?',
        'I am from...': 'Soy de...',
        'How old are you?': '¿Cuántos años tienes?',
        'I am ... years old': 'Tengo ... años',
        'What time is it?': '¿Qué hora es?',
        'It’s time to go': 'Es hora de ir',
        'Can I help you?': '¿Puedo ayudarte?',
        'I need help': 'Necesito ayuda',
        'Where is the bathroom?': '¿Dónde está el baño?',
        'I don’t understand': 'No entiendo',
        'I don’t speak Spanish': 'No hablo español',
        'I speak a little Spanish': 'Hablo un poco de español',
        'Can you repeat?': '¿Puedes repetir?',
        'How much is this?': '¿Cuánto cuesta esto?',
        'It’s too expensive': 'Es demasiado caro',
        'I’m hungry': 'Tengo hambre',
        'I’m thirsty': 'Tengo sed',
        'Let’s go!': '¡Vamos!',
        'I’m tired': 'Estoy cansado/a',
        'What do you do?': '¿Qué haces?',
        'I am a student': 'Soy estudiante',
        'I am a teacher': 'Soy maestro/a',
        'I work in...': 'Trabajo en...',
        'I like...': 'Me gusta...',
        'I don’t like...': 'No me gusta...',
        'Do you like...?': '¿Te gusta...?',
        'I’m sorry': 'Lo siento',
        'Excuse me, sir': 'Perdón, señor',
        'Excuse me, madam': 'Perdón, señora',
        'Good afternoon': 'Buenas tardes',
        'Good evening': 'Buenas noches',
        'Welcome': 'Bienvenido/a',
        'Good luck': 'Buena suerte',
        'Enjoy your meal': 'Buen provecho',
        'What’s up?': '¿Qué pasa?',
        'Nothing much': 'Nada',
        'See you later': 'Hasta luego',
        'Take care': 'Cuídate',
        'Have a nice day': 'Que tengas un buen día',
        'Cheers': 'Salud',
        'I’m going to the store': 'Voy a la tienda'
    },
    'French': {
        'Hello': 'Bonjour',
        'Goodbye': 'Au revoir',
        'Thank you': 'Merci',
        'Please': 'S’il vous plaît',
        'Sorry': 'Désolé',
        'Yes': 'Oui',
        'No': 'Non',
        'Excuse me': 'Excusez-moi',
        'Good morning': 'Bonjour',
        'Good night': 'Bonne nuit',
        'How are you?': 'Comment ça va?',
        'I love you': 'Je t’aime',
        'What is your name?': 'Comment tu t’appelles?',
        'My name is...': 'Je m’appelle...',
        'Where are you from?': 'D’où viens-tu?',
        'I am from...': 'Je viens de...',
        'How old are you?': 'Quel âge as-tu?',
        'I am ... years old': 'J’ai ... ans',
        'What time is it?': 'Quelle heure est-il?',
        'It’s time to go': 'Il est temps de partir',
        'Can I help you?': 'Puis-je vous aider?',
        'I need help': 'J’ai besoin d’aide',
        'Where is the bathroom?': 'Où sont les toilettes?',
        'I don’t understand': 'Je ne comprends pas',
        'I don’t speak French': 'Je ne parle pas français',
        'I speak a little French': 'Je parle un peu français',
        'Can you repeat?': 'Peux-tu répéter?',
        'How much is this?': 'Combien ça coûte?',
        'It’s too expensive': 'C’est trop cher',
        'I’m hungry': 'J’ai faim',
        'I’m thirsty': 'J’ai soif',
        'Let’s go!': 'Allons-y!',
        'I’m tired': 'Je suis fatigué(e)',
        'What do you do?': 'Que fais-tu?',
        'I am a student': 'Je suis étudiant(e)',
        'I am a teacher': 'Je suis professeur(e)',
        'I work in...': 'Je travaille dans...',
        'I like...': 'J’aime...',
        'I don’t like...': 'Je n’aime pas...',
        'Do you like...?': 'Aimes-tu...?',
        'I’m sorry': 'Je suis désolé(e)',
        'Excuse me, sir': 'Excusez-moi, monsieur',
        'Excuse me, madam': 'Excusez-moi, madame',
        'Good afternoon': 'Bon après-midi',
        'Good evening': 'Bonsoir',
        'Welcome': 'Bienvenue',
        'Good luck': 'Bonne chance',
        'Enjoy your meal': 'Bon appétit',
        'What’s up?': 'Ça va?',
        'Nothing much': 'Pas grand-chose',
        'See you later': 'À plus tard',
        'Take care': 'Prends soin de toi',
        'Have a nice day': 'Bonne journée',
        'Cheers': 'Santé',
        'I’m going to the store': 'Je vais au magasin'
    },
    'Italian': {
        'Hello': 'Ciao',
        'Goodbye': 'Arrivederci',
        'Thank you': 'Grazie',
        'Please': 'Per favore',
        'Sorry': 'Mi dispiace',
        'Yes': 'Sì',
        'No': 'No',
        'Excuse me': 'Mi scusi',
        'Good morning': 'Buongiorno',
        'Good night': 'Buonanotte',
        'How are you?': 'Come stai?',
        'I love you': 'Ti amo',
        'What is your name?': 'Come ti chiami?',
        'My name is...': 'Mi chiamo...',
        'Where are you from?': 'Di dove sei?',
        'I am from...': 'Sono di...',
        'How old are you?': 'Quanti anni hai?',
        'I am ... years old': 'Ho ... anni',
        'What time is it?': 'Che ora è?',
        'It’s time to go': 'È ora di andare',
        'Can I help you?': 'Posso aiutarti?',
        'I need help': 'Ho bisogno di aiuto',
        'Where is the bathroom?': 'Dove è il bagno?',
        'I don’t understand': 'Non capisco',
        'I don’t speak Italian': 'Non parlo italiano',
        'I speak a little Italian': 'Parlo un po’ di italiano',
        'Can you repeat?': 'Puoi ripetere?',
        'How much is this?': 'Quanto costa?',
        'It’s too expensive': 'È troppo caro',
        'I’m hungry': 'Ho fame',
        'I’m thirsty': 'Ho sete',
        'Let’s go!': 'Andiamo!',
        'I’m tired': 'Sono stanco/a',
        'What do you do?': 'Cosa fai?',
        'I am a student': 'Sono uno studente/una studentessa',
        'I am a teacher': 'Sono un insegnante',
        'I work in...': 'Lavoro in...',
        'I like...': 'Mi piace...',
        'I don’t like...': 'Non mi piace...',
        'Do you like...?': 'Ti piace...?',
        'I’m sorry': 'Mi dispiace',
        'Excuse me, sir': 'Mi scusi, signore',
        'Excuse me, madam': 'Mi scusi, signora',
        'Good afternoon': 'Buon pomeriggio',
        'Good evening': 'Buona sera',
        'Welcome': 'Benvenuto/a',
        'Good luck': 'Buona fortuna',
        'Enjoy your meal': 'Buon appetito',
        'What’s up?': 'Che succede?',
        'Nothing much': 'Niente di che',
        'See you later': 'A più tardi',
        'Take care': 'Stammi bene',
        'Have a nice day': 'Buona giornata',
        'Cheers': 'Salute',
        'I’m going to the store': 'Vado al negozio'
    }
}

def translator():
  language = input('Select a language: ')
  word = input('Enter a word: ')

  def translate_word():
      if word in translations.get(language, {}):
          return print(f"The translation of '{word}' in {language} is: {translations[language][word]}")
      else:
          return f'Word not found in {language} dictionary'
    
  return translate_word
    
translate_to_spanish = translator()
print(translate_to_spanish()) # Output: hola